# ==============================
# SERVICES
# ==============================

services:

  # ------------------------------
  # Postgres container 1
  # ------------------------------
  db1:
    image: ${POSTGRES_IMAGE}
    restart: always
    ports: 
      # PG port is exposed so that we can connect
      # to PG from outside through localhost:5432
      - "${POSTGRES_PUBLIC_PORT}:5432"
    volumes:
      - db1_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  # ------------------------------
  # Postgres container 2
  # ------------------------------
  db2:
    image: ${POSTGRES_IMAGE}
    restart: always
    ports: 
      # PG port is exposed so that we can connect
      # to PG from outside through localhost:5432
      - "${POSTGRES_PUBLIC_PORT2}:5432"    
    volumes:
      - db2_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}      
  
  # ------------------------------
  # pgAdmin
  # ------------------------------
  pgadmin:
    image: ${PGADMIN_IMAGE}
    restart: always
    volumes:
      - pgadmin:/var/lib/pgadmin
      - ${PGADMIN_SERVER_JSON_FILE}:/pgadmin4/servers.json
    depends_on:
      - db1
      - db2
    environment: 
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "${PGADMIN_PUBLIC_PORT}:80"

# ==============================
# VOLUMES
# ==============================
volumes:
  db1_data:
  db2_data:
  pgadmin:
